name: breadcrumb
author:
  name: Divyendra M
  googleplus: https://google.com/+DivyendraM/
  

paginate: 5

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables"]

relative_permalinks: false
permalink: /:year/:month/:title.html

exclude: ['README.md', 'LICENSE.txt']
